FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 AS builder

ENV SOURCE_DIR=/maestro
WORKDIR $SOURCE_DIR
COPY . $SOURCE_DIR

# Pass GIT Commit to the container for maestro agent
ARG GIT_COMMIT
ENV GIT_COMMIT=${GIT_COMMIT}
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
RUN make binary BUILD_OPTS="-tags strictfipsruntime -ldflags \"-X k8s.io/component-base/version.gitVersion=v0.0.0-main -X k8s.io/component-base/version.gitCommit=${GIT_COMMIT}\""

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

# Pass GIT Commit to the container for maestro server
ARG GIT_COMMIT
ENV GIT_COMMIT=${GIT_COMMIT}

COPY --from=builder /maestro/maestro /usr/local/bin/

USER 10001

EXPOSE 8000
ENTRYPOINT ["/usr/local/bin/maestro", "server"]

LABEL name="multicluster-engine/maestro-rhel9" \
      cpe="cpe:/a:redhat:multicluster_engine:2.17::el9" \
      com.redhat.component="maestro" \
      vendor="Red Hat, Inc." \
      summary="Maestro server for multi-cluster resource management" \
      description="Maestro server leverages CloudEvents to transport Kubernetes resources to target clusters and collect status updates via REST and gRPC APIs" \
      io.k8s.description="Maestro server leverages CloudEvents to transport Kubernetes resources to target clusters and collect status updates via REST and gRPC APIs" \
      io.k8s.display-name="maestro" \
      io.openshift.tags="maestro"

# Additional tags for Konflux to generate latest tag
LABEL konflux.additional-tags="latest"
